### ISSUE TITLE
Issue with Oracle Cloud deployment and aarch64 system

### ISSUE THREAD

**Issue by sha0x404** [winglessraven/AMP-Discord-Bot#56]
As per the title, the plugin is installed and appears in AMP, but it is not online on Discord. There are no errors. Version 2.4.6 - 20230802.1.

 - OS: Debian
 - AMP Build: Version 2.4.6 - 20230802.1.

**Comment by winglessraven** [comment]
Can you share the AMP logs for the instance?

**Comment by winglessraven** [comment]
Great, thanks. The AMP version is fine - all of mine are on that version and working OK.

Looks like the bot holds on `Connecting` so first thing to check would be that the bot can reach the Discord API.

See if you get a 200 response from `curl -I https://discordapp.com/api/v10/gateway`

If that is OK then we know the server can reach the API without issue so the next step is to try getting some more logging from the bot.

Attached is a version of the bot plugin with verbose Discord logging (example below). Unzip and add that to your server instead of the other version and try connecting again (after restarting the instance). Hopefully the logs will pick up the issue.

[DiscordBotPlugin.zip](https://github.com/winglessraven/AMP-Discord-Bot/files/12300555/DiscordBotPlugin.zip)

```
[09:15:31] [Logger:admin Activity] : Changing setting DiscordBotPlugin.DiscordBotSettings.BotActive to True
[09:15:31] [DiscordBot:admin Info] : 09:15:31 Discord     Discord.Net v1.0.0 (API v10)
[09:15:31] [DiscordBot:admin Info] : 09:15:31 Gateway     Connecting
[09:15:31] [DiscordBot:admin Info] : 09:15:31 Rest        GET gateway/bot: 236.81 ms
[09:15:32] [DiscordBot:admin Info] : 09:15:32 Gateway     Connected
[09:15:32] [DiscordBot:admin Info] : 09:15:32 Gateway     
Connected to <My Discord Server>
[09:15:32] [DiscordBot:admin Info] : Base command for bot: starbound
[09:15:32] [DiscordBot:admin Info] : 09:15:32 Rest        PUT applications/<Application ID>/commands: 304.67 ms
[09:15:32] [DiscordBot:admin Info] : 09:15:32 Gateway     Ready
```

**Comment by winglessraven** [comment]
This is a strange one. Out of curiosity if you put an invalid token in do you get a 401 error in the AMP log?

I've tested on ARM previously and it worked OK, but will set one up to double check.

Are you also running in Docker?

**Comment by sha0x404** [comment]
This is the log with the completely wrong token:
[https://pastebin.com/raw/0VwsmWWB]( https://pastebin.com/raw/0VwsmWWB)

This is the log with the token that has the correct number of characters: 
[https://pastebin.com/raw/w4YznF2X](https://pastebin.com/raw/w4YznF2X)

These are the settings for my bot:
PUBLIC BOT=disabled
REQUIRES OAUTH2 CODE GRANT=disabled
PRESENCE INTENT=enabled
SERVER MEMBERS INTENT=enabled
MESSAGE CONTENT INTENT=enabled
 
Regarding my installation: I have installed amp on an Ubuntu 22.04.3 LTS (Architecture: aarch64)  with an ARM processor, without using the reverse proxy provided by amp, but instead manually setting up Traefik within Docker.

**Comment by winglessraven** [comment]
I've just managed to replicate on aarch64 (Oracle Cloud). 

I get the same hang on `Connecting`. Never times out, never connects. 

I'll try to do some digging. I'm wondering if something in the Discord.Net library I'm using isn't compatible.

**Comment by sha0x404** [comment]
If it can help you: in the past, I successfully used your project about a month ago, always on the same machine. But one day, it stopped working, and after completely formatting the machine for other reasons, the bot no longer worked.

**Comment by winglessraven** [comment]
I also had it working previously on Oracle Cloud. But like you, since I set a new machine up it is no longer working.

I've tried some basic debugging by disabling ipv6, installing some extra dotnet runtimes and nothing so far is helping.

I will ask around in the Discord.Net Discord to see if there are any known aarch64 issues.

**Comment by winglessraven** [comment]
I'm actually stuck with this one.

I have added some extra debugging to try and narrow down where the issue is and it does point to the connection method in the Discord.Net library I'm using (gets stuck in 'Connecting' state - even with an incorrect API key). However, what the problem is I don't know.

I asked on their Discord and seems like there are no known issues, and some users there are using Oracle Cloud without issues.

I will raise an issue on their GitHub page to see if any cause can be identified.

**Comment by winglessraven** [comment]
https://github.com/discord-net/Discord.Net/issues/2750

**Comment by winglessraven** [comment]
I've managed to get it working on my Oracle test env - please give this one a try.

[DiscordBotPlugin.zip](https://github.com/winglessraven/AMP-Discord-Bot/files/12312238/DiscordBotPlugin.zip)

Something to do with the Discord endpoint, appending "/bot" to the default gateway got it working on mine (no idea why though!).

**Comment by sha0x404** [comment]
I still made a test with the latest version, nothing new, here's the log:
[https://pastebin.com/raw/BkwWmDC7](https://pastebin.com/raw/BkwWmDC7)

**Comment by winglessraven** [comment]
Forgot to say - enable the debug option in the bot settings, then restart it.

**Comment by sha0x404** [comment]
I come with good news: after removing the DiscordBotPlugin.kvp configuration file, restarting the instance, clearing the cache, and putting the regenerated token, I was able to successfully start the bot! What exactly was the problem? 
Below the log with the developer enabled.
[https://pastebin.com/raw/8YQDkP3q]( https://pastebin.com/raw/8YQDkP3q)
 As regards the final version of the product can I keep this or will it be released in the official version soon?

**Comment by winglessraven** [comment]
The only thing I've changed is to set the gateway host manually (rather than let the Discord.Net library grab it). 

But you'll probably find it still doesn't work correctly. e.g. no commands going through to create the info panel etc.

This line here in the log is the next issue:
`[19:04:33] [DiscordBot Info]      : 19:04:33 Gateway     A Ready handler is blocking the gateway task.`

**Comment by sha0x404** [comment]
If you have the time and availability, perhaps creating a virtual environment for arm64 to try running the bot could resolve the dilemma of whether the issue is due to some configuration that Oracle has or the specific architecture type.

**Comment by winglessraven** [comment]
Good idea. I'll see if I can find my old Raspberry Pi and give it a go on there.

**Comment by winglessraven** [comment]
I can confirm it's not just Oracle so seems like the architecture. Tested on Ubuntu 23.04 (GNU/Linux 6.2.0-1004-raspi aarch64) and have exactly the same issue.

Maybe the ARM build of AMP has some packages missing that are required for Discord.Net to connect correctly.

Someone else did check Discord.Net for me on aarch64 successfully but they were targeting .Net Framework v6.0 with their test. AMP targets .Net Framework v4.8.

**Comment by sha0x404** [comment]
any update?

**Comment by winglessraven** [comment]
I've tried multiple things but I just can't get it to work. Issue is, I can't even debug what the root cause is because the connection part that is hanging is in the Discord.Net library I'm using and full logging isn't showing me what the error is.

I will try some other tests, but running out of ideas.

**Comment by winglessraven** [comment]
So randomly I thought I'd update *everything* I could on the server. Checked the list with `apt list --upgradeable`, updated everything, rebooted, and now it's working again for me...

```
[13:19:32] [DiscordBot Info]      : Discord Bot Activated
[13:19:32] [DiscordBot Info]      : 13:19:32 Discord     Discord.Net v1.0.0 (API v10)
[13:19:32] [DiscordBot Info]      : 13:19:32 Gateway     Connecting
[13:19:32] [Webserver Info]       : Websockets are enabled.
[13:19:32] [Logger Info]          : RouterTimer@10Hz with 2 jobs started
[13:19:32] [Logger Info]          : Webserver started on http://127.0.0.1:8081
[13:19:32] [Core Info]            : Checking for AMP updates...
[13:19:32] [Logger Info]          : Startup mode is StartApplication.
[13:19:32] [Logger Info]          : Java located at /usr/lib/jvm/temurin-18-jdk-arm64/bin/java
[13:19:33] [Core Info]            : AMP is up to date.
[13:19:33] [DiscordBot Info]      : 13:19:33 Gateway     Connected
[13:19:34] [Logger Info]          : Modpack cache is up-to-date.
[13:19:35] [Logger Info]          : Using 'Official' compatibility mode.
[13:19:39] [DiscordBot Info]      : Base command for bot: minecraft-test
[13:19:39] [DiscordBot Info]      : 13:19:39 Gateway     Ready
```

**Comment by sha0x404** [comment]
I confirm that the problem has been randomly resolved and hopefully it won't happen again. I will keep the issue open for further testing.

**Comment by sha0x404** [comment]
No issues in over 3 weeks the problem seems to have resolved itself. I close

**Comment by sha0x404** [comment]
The same problem came back to me, unbelievable, maybe it has to do with the first days of the month? xD
the log follows:
https://pastebin.com/raw/5u1aZFc2

**Comment by winglessraven** [comment]
At this point it's looking like something out of my control. I will bring it up on the Discord.Net group again but as AMP is A lower Net version than they support I don't imagine I'll get anywhere again 😔

**Comment by winglessraven** [comment]
I can confirm I have the same issue again on my test Oracle machine. Probably more than a coincidence that yours and mine have been knocked out at the same time.

**Comment by winglessraven** [comment]
For info - it appears to be running again on my test machine with no change in configuration on my end. I'm pretty sure whatever causes these connection issues is outside of my control.
