### ISSUE TITLE
FR:Timed auto messages

### ISSUE THREAD

**Issue by DrFiishy** [winglessraven/AMP-Discord-Bot#70]
Was wondering if it would be possible to add in auto messages that delete after a certain amount of time to announce things.

So lets say you restart the game server every 12 hours, the bot then announces the restart 5min before the restart, deletes the chat and posts a new one when there is 3min left of the timer and does the same when there is 1min left.

**Comment by winglessraven** [comment]
I had a quick look into this yesterday. While it is possible, there are lots of caveats surrounding where the data of the restart schedule comes from etc. 

Was thinking I could hook into the AMP scheduler to pick up scheduled restarts but issue with that is that if it's done via the method below then we have no way of knowing if the command is a restart, since it's different for every server.

![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/fcdffb15-0471-4d12-a747-b1b79c885e36)

Perhaps the best option for this is to just use Discord webhooks directly from the scheduler.
